### ISSUE TITLE
brew install に失敗する

### ISSUE THREAD

**Issue by cw-ataka** [ishkawa/ls2xs#2]
先日、Pull Request を差し上げた @ataka です。

Pull Request のマージありがとうございます。
## インストールに失敗

XCode 7 を使って `brew install` しようとするとエラーが出ます。

https://github.com/ishkawa/homebrew-formulae が ver 0.0.1 のタグを指しているのが原因です。

適当な version (tag) を作成し、 https://github.com/ishkawa/homebrew-formulae のポインターを新しい version に変えれば解決すると思います。

Github では tag の Pull Request まで送れないようなので、私の手では解決できませんでした。すみません。

**Comment by ishkawa** [comment]
報告していただき、ありがとうございます！

このリポジトリにタグを追加してformulaも更新しましたので、
再度`brew install ishkawa/formulae/ls2xs`を試していただけますか？

**Comment by ataka** [comment]
@ishkawa 

```
$ brew uninstall ls2xs --force
$ brew install ishkawa/formulae/ls2xs
```

上記コマンドを実行して、`ls2xs` v0.0.2 が XCode 7 でインストールできることを確認しました。
ありがとうございます :smile:

**Comment by ishkawa** [comment]
:sparkles:
